apiVersion: apps/v1
kind: Deployment
metadata:
  name: elasticsearch
  labels:
    app: elasticsearch
  namespace: fyp-backend 
spec:
  replicas: 1 
  selector:
    matchLabels:
      app: elasticsearch
  template:
    metadata:
      labels:
        app: elasticsearch
    spec:
      containers:
        - name: elasticsearch
          image: docker.elastic.co/elasticsearch/elasticsearch:8.6.0  
          imagePullPolicy: Always
          env:
            - name: discovery.type
              value: single-node  p
            - name: ES_JAVA_OPTS
              value: "-Xmx1g -Xms1g"  
          ports:
            - containerPort: 9200  # The default port for Elasticsearch HTTP API
            - containerPort: 9300  # The default port for internal communication (cluster communication)
          resources:
            requests:
              cpu: "256m"
              memory: "512m"
            limits:
              cpu: "1"
              memory: "512"
          volumeMounts:
            - name: es-data
              mountPath: /usr/share/elasticsearch/data
      volumes:
        - name: es-data
          emptyDir: {}  
         
---

apiVersion: v1
kind: Service
metadata:
  name: elasticsearch
  namespace: fyp-backend  # Replace with your desired namespace
spec:
  selector:
    app: elasticsearch
  ports:
    - protocol: TCP
      port: 9200  # External port to access Elasticsearch
      targetPort: 9200  # Internal port of the container
    - protocol: TCP
      port: 9300  # Internal cluster communication port (optional but recommended for clustered setups)
      targetPort: 9300
  type: LoadBalancer  # For internal access, use LoadBalancer if you need external access
          