apiVersion: apps/v1
kind: Deployment
metadata:
  name: elasticsearch
  labels:
    app: elasticsearch
  namespace: fyp-backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: elasticsearch
  template:
    metadata:
      labels:
        app: elasticsearch
    spec:
      containers:
        - name: elasticsearch
          image: docker.elastic.co/elasticsearch/elasticsearch:8.6.0
          imagePullPolicy: Always
          env:
            - name: discovery.type
              value: single-node
            - name: ES_JAVA_OPTS
              value: "-Xmx1g -Xms1g"
            - name: bootstrap.memory_lock
              value: "false"
            # Critical security and network settings
            - name: xpack.security.enabled
              value: "false"
            - name: network.host
              value: 0.0.0.0
            - name: http.port
              value: "9200"
          ports:
            - containerPort: 9200
            - containerPort: 9300
          resources:
            requests:
              cpu: "500m"
              memory: "1Gi"
            limits:
              cpu: "900m"
              memory: "2Gi"
          volumeMounts:
            - name: es-data
              mountPath: /usr/share/elasticsearch/data
          readinessProbe:  # Add health check
            httpGet:
              path: /_cluster/health
              port: 9200
            initialDelaySeconds: 30
            periodSeconds: 10
      volumes:
        - name: es-data
          emptyDir: {}

---

apiVersion: v1
kind: Service
metadata:
  name: elasticsearch
  namespace: fyp-backend
spec:
  selector:
    app: elasticsearch
  ports:
    - name: http
      protocol: TCP
      port: 9200
      targetPort: 9200
  type: ClusterIP  # Better for internal access