apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-golang-backend
  labels:
    app: my-golang-backend
  namespace: fyp-backend  
spec:
  replicas: 2
  selector:
    matchLabels:
      app: my-golang-backend
  template:
    metadata:
      labels:
        app: my-golang-backend
    spec:
      imagePullSecrets:
        - name: dockerhub-secret
      containers:
        - name: my-golang-backend
          image: f3130/my-golang-backend:latest
          ports:
            - containerPort: 8080
          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"
            limits:
              cpu: "500m"
              memory: "256Mi"
          env:
            - name: ENV
              value: "production"