apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-golang-backend
  labels:
    app: my-golang-backend
  namespace: fyp-backend  
spec:
  replicas: 1
  selector:
    matchLabels:
      app: my-golang-backend
  template:
    metadata:
      labels:
        app: my-golang-backend
    spec:
      imagePullSecrets:
        - name: dockerhub-secret
      containers:
        - name: my-golang-backend
          image: f3130/my-golang-backend:v2.1
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          resources:
            requests:
              cpu: "256m"
              memory: "256Mi"
            limits:
              cpu: "550m"
              memory: "550Mi"
          env:
            - name: ENV
              value: "production"
          envFrom:
            - configMapRef:
               name: app-config

---

apiVersion: v1
kind: Service
metadata:
  name: app
spec:
  selector:
    app: my-golang-backend
  ports:
  - protocol: TCP
    port: 8080  
    targetPort: 8080
  type: LoadBalancer  
                