curl -X POST http://localhost:8080/products/new-product \
-H "Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE3Mzk0NDg2NzUsInJvbGUiOiJhZG1pbiIsInVzZXJJZCI6MSwidXNlcm5hbWUiOiJ6b3JvIn0.r0HGLt3qXjOM0i_oXr9Njgsp91kNVQX0az5sIiz3DSE" \
-F "name=Tractor seeds" \
-F "description=sunflower chia seeds" \
-F "userId=1" \
-F "categoryName=seeds" \
-F "price=500" \
-F "image=@/home/faizan/Pictures/ss.png"

//For windows
curl.exe -X POST http://localhost:8080/products/new-product `
-H "Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE3MzkwMjQzNzIsInJvbGUiOiJhZG1pbiIsInVzZXJJZCI6MiwidXNlcm5hbWUiOiJ6b3JvIn0.rw8-3ZcJbfVU1CBtLOYRt2jNl36MpE3E46J4YLISFuo" `
-F "name=Tractor seeds" `
-F "description=sunflower chia seeds " `
-F "userId=1" `
-F "categoryName=seeds" `
-F "price= 500"
-F "image=@/home/faizan/Pictures/ss.png" 