apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-chat-backend
  labels:
    app: my-chat-backend
  namespace: fyp-backend  
spec:
  replicas: 1
  selector:
    matchLabels:
      app: my-chat-backend
  template:
    metadata:
      labels:
        app: my-chat-backend
    spec:
      imagePullSecrets:
        - name: dockerhub-secret
      containers:
        - name: my-chat-backend
          image: f3130/backend-chat:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8081
          resources:
            requests:
              cpu: "256m"
              memory: "256Mi"
            limits:
              cpu: "550m"
              memory: "550Mi"
          envFrom:
            - configMapRef:
               name: app-config              

---

apiVersion: v1
kind: Service
metadata:
  name: chat
spec:
  selector:
    app: my-chat-backend
  ports:
  - protocol: TCP
    port: 8081  
    targetPort: 8081
  type: LoadBalancer  
                