name: Test Project
on: 
  push:
    branches:
      - main
  workflow_dispatch:    
jobs:
    # deploy-main:
    #     runs-on: fyp-backend
    #     steps:
    #         - name: Get code
    #           uses: actions/checkout@v3
    #         - name: Log in to Docker Hub
    #           uses: docker/login-action@v3
    #           with:
    #             username: ${{ secrets.DOCKER_USERNAME }}
    #             password: ${{ secrets.DOCKER_PASSWORD }}
    #         - name: Build Docker Image
    #           run: |
    #             cd backend
    #             docker build -t f3130/my-golang-backend:v2.2 .
    #         - name: Push Docker Image
    #           run: |
    #             docker push f3130/my-golang-backend:v2.2
                
    # deploy-chat:
    #     runs-on: fyp-backend
    #     steps:
    #         - name: Get code
    #           uses: actions/checkout@v3
    #         - name: Log in to Docker Hub
    #           uses: docker/login-action@v3
    #           with:
    #             username: ${{ secrets.DOCKER_USERNAME }}
    #             password: ${{ secrets.DOCKER_PASSWORD }}
    #         - name: Build Docker Image
    #           run: |
    #             cd "backend/ChatAgromart(service)"
    #             docker build -t f3130/backend-chat:latest .
    #         - name: Push Docker Image
    #           run: |
    #             docker push f3130/backend-chat:latest
                
    deploy-search:
        runs-on: fyp-backend
        steps:
          - name: Get code
            uses: actions/checkout@v3
          - name: Log in to Docker Hub
            uses: docker/login-action@v3
            with:
              username: ${{ secrets.DOCKER_USERNAME }}
              password: ${{ secrets.DOCKER_PASSWORD }}
          - name: Build Docker Image
            run: |
              cd "backend/ElasticSearch(service)"
              ls
              docker build -t f3130/backend-search:latest .
          - name: Push Docker Image
            run: |
              docker push f3130/backend-search:latest
                        

