name: Test Project
on: 
  push:
    branches:
      - main
  workflow_dispatch:    
jobs:
    deploy-main:
        runs-on: ubuntu-latest
        steps:
            - name: Get code
              uses: actions/checkout@v3
            - name: Log in to Docker Hub
              uses: docker/login-action@v3
              with:
                username: ${{ secrets.DOCKER_USERNAME }}
                password: ${{ secrets.DOCKER_PASSWORD }}
            - name: print directory
              run: |
                cd backend
                ls    
            - name: Build Docker Image
              run: |
                cd backend
                docker build -t f3130/my-golang-backend:latest .
            - name: Push Docker Image
              run: |
                docker push f3130/my-golang-backend:latest
    # deploy-chat:
    #     runs-on: ubuntu-latest
    #     steps:
    #         - name: Get code
    #           uses: actions/checkout@v3
    #         - name: Change Directory
    #           run: cd backend/ChatAgromart  
    #         - name: Log in to Docker Hub
    #           uses: docker/login-action@v3
    #           with:
    #             username: ${{ secrets.DOCKER_USERNAME }}
    #             password: ${{ secrets.DOCKER_PASSWORD }}
    #         - name: Build Docker Image
    #           run: |
    #             docker build -t f3130/backend-chat:latest .
    #         - name: Push Docker Image
    #           run: |
    #             docker push f3130/backend-chat:latest    

